"""
Structured Constraint Schema and Checker for Constraint-Adherence Testing

Defines a machine-checkable constraint format that mirrors the natural language
constraints generated by create_dataset/src/procedural_template.py:

    - Layer count (exact, min, max)
    - Material restrictions (strict, helpful, extra, restrict, any)
    - Individual thickness bounds
    - Relative thickness comparisons
    - Adjacency requirements
    - Total / per-layer thickness bounds
    - Layer identity (first/last layer must/must not be a material)

Usage:
    constraints = StructuredConstraints.from_dict(json.loads(row['constraints']))
    result = check_constraints(predicted_materials, predicted_thicknesses, constraints)
    print(result.summary())
"""

from __future__ import annotations
import json
from dataclasses import dataclass, field, asdict
from typing import Optional, List, Dict, Any


@dataclass
class StructuredConstraints:
    """Machine-checkable constraint annotations for a test example."""

    # Layer count constraint (from get_layers_fragment)
    layer_count_type: str = "none"          # "exact" | "min" | "max" | "none"
    layer_count_value: Optional[int] = None  # None if type == "none"

    # Material constraint (from get_materials_fragment)
    materials_type: str = "any"             # "strict" | "helpful" | "extra" | "restrict" | "any"
    allowed_materials: List[str] = field(default_factory=list)   # for strict/helpful/extra
    forbidden_materials: List[str] = field(default_factory=list) # for restrict

    # Additional constraints (from additional_constraints)
    additional: List[Dict[str, Any]] = field(default_factory=list)
    # Each dict is one of:
    #   {"type": "adjacency", "material_a": str, "material_b": str, "must_be_adjacent": bool}
    #   {"type": "relative_thickness", "material_a": str, "material_b": str,
    #        "relation": "thicker"|"thinner"|"equal"}
    #   {"type": "individual_thickness", "material": str, "bound": "min"|"max"|"exact",
    #        "value_nm": int}
    #   {"type": "total_thickness_sum", "bound": "max"|"min", "value_nm": int}
    #   {"type": "total_thickness_each", "bound": "max"|"min", "value_nm": int}
    #   {"type": "layer_identity", "position": "first"|"last", "material": str,
    #        "must_be": bool}

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False)

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> StructuredConstraints:
        return cls(**d)

    @classmethod
    def from_json(cls, s: str) -> StructuredConstraints:
        return cls.from_dict(json.loads(s))


@dataclass
class ConstraintCheckResult:
    """Result of checking a single constraint."""
    constraint_type: str
    passed: bool
    detail: str = ""


@dataclass
class ConstraintResult:
    """Aggregate result of checking all constraints for one example."""
    checks: List[ConstraintCheckResult] = field(default_factory=list)
    # Set breakdown for strict/helpful/extra material constraints (informational)
    materials_set_detail: Optional[Dict[str, Any]] = None

    @property
    def all_passed(self) -> bool:
        return all(c.passed for c in self.checks)

    @property
    def n_passed(self) -> int:
        return sum(1 for c in self.checks if c.passed)

    @property
    def n_failed(self) -> int:
        return sum(1 for c in self.checks if not c.passed)

    @property
    def n_total(self) -> int:
        return len(self.checks)

    def summary(self) -> str:
        lines = [f"{self.n_passed}/{self.n_total} constraints passed"]
        for c in self.checks:
            status = "PASS" if c.passed else "FAIL"
            lines.append(f"  [{status}] {c.constraint_type}: {c.detail}")
        if self.materials_set_detail:
            d = self.materials_set_detail
            lines.append(f"  [INFO] materials_{d['type']} set analysis: "
                         f"jaccard={d['jaccard']:.2f}, "
                         f"missing={d['missing']}, extra={d['extra_used']}")
        return "\n".join(lines)


def check_constraints(
    materials: List[str],
    thicknesses: List[int],
    constraints: StructuredConstraints,
) -> ConstraintResult:
    """
    Check if a predicted structure satisfies all structured constraints.

    Args:
        materials: Predicted material list (e.g., ["SiO2", "Ag", "TiO2"])
        thicknesses: Predicted thickness list in nm (e.g., [100, 50, 75])
        constraints: Structured constraint annotations

    Returns:
        ConstraintResult with per-constraint pass/fail details
    """
    result = ConstraintResult()
    n_layers = len(materials)

    # --- Layer count ---
    if constraints.layer_count_type == "exact":
        ok = n_layers == constraints.layer_count_value
        result.checks.append(ConstraintCheckResult(
            "layer_count_exact", ok,
            f"expected {constraints.layer_count_value}, got {n_layers}"))
    elif constraints.layer_count_type == "min":
        ok = n_layers >= constraints.layer_count_value
        result.checks.append(ConstraintCheckResult(
            "layer_count_min", ok,
            f"min {constraints.layer_count_value}, got {n_layers}"))
    elif constraints.layer_count_type == "max":
        ok = n_layers <= constraints.layer_count_value
        result.checks.append(ConstraintCheckResult(
            "layer_count_max", ok,
            f"max {constraints.layer_count_value}, got {n_layers}"))

    # --- Material restrictions ---
    mat_set = set(materials)
    allowed_set = set(constraints.allowed_materials)
    forbidden_set = set(constraints.forbidden_materials)

    if constraints.materials_type in ("strict", "helpful", "extra"):
        # Compute set breakdown for all three types
        missing = allowed_set - mat_set
        extra_mats = mat_set - allowed_set
        intersection = mat_set & allowed_set
        union = mat_set | allowed_set
        result.materials_set_detail = {
            'type': constraints.materials_type,
            'is_subset': mat_set < allowed_set,
            'is_exact': mat_set == allowed_set,
            'is_superset': allowed_set < mat_set,
            'jaccard': len(intersection) / max(len(union), 1),
            'missing': sorted(missing),
            'extra_used': sorted(extra_mats),
            'allowed': sorted(allowed_set),
            'predicted': sorted(mat_set),
        }

        if constraints.materials_type == "strict":
            # Constraint: all required materials must be present (extras OK)
            ok = allowed_set.issubset(mat_set)
            result.checks.append(ConstraintCheckResult(
                "materials_strict", ok,
                f"required {sorted(allowed_set)}, got {sorted(mat_set)}"
                + (f", missing: {sorted(missing)}" if missing else "")))
        # helpful and extra are suggestions — not added to checks
    elif constraints.materials_type == "restrict":
        # Must not use any forbidden materials
        overlap = mat_set & forbidden_set
        ok = len(overlap) == 0
        result.checks.append(ConstraintCheckResult(
            "materials_restrict", ok,
            f"forbidden {sorted(forbidden_set)}, used {sorted(overlap)}" if overlap
            else f"forbidden {sorted(forbidden_set)}, none used"))

    # --- Additional constraints ---
    for c in constraints.additional:
        ctype = c["type"]

        if ctype == "adjacency":
            mat_a, mat_b = c["material_a"], c["material_b"]
            must_adj = c["must_be_adjacent"]
            if mat_a in materials and mat_b in materials:
                # Check all occurrences
                indices_a = [i for i, m in enumerate(materials) if m == mat_a]
                indices_b = [i for i, m in enumerate(materials) if m == mat_b]
                adjacent = any(abs(ia - ib) == 1
                               for ia in indices_a for ib in indices_b)
                ok = adjacent == must_adj
                verb = "must be" if must_adj else "must not be"
                result.checks.append(ConstraintCheckResult(
                    "adjacency", ok,
                    f"{mat_a} {verb} adjacent to {mat_b}, adjacent={adjacent}"))

        elif ctype == "relative_thickness":
            mat_a, mat_b = c["material_a"], c["material_b"]
            relation = c["relation"]
            if mat_a in materials and mat_b in materials:
                idx_a = materials.index(mat_a)
                idx_b = materials.index(mat_b)
                t_a, t_b = thicknesses[idx_a], thicknesses[idx_b]
                if relation == "thicker":
                    ok = t_a > t_b
                elif relation == "thinner":
                    ok = t_a < t_b
                else:  # equal
                    ok = t_a == t_b
                result.checks.append(ConstraintCheckResult(
                    "relative_thickness", ok,
                    f"{mat_a}({t_a}nm) {relation} {mat_b}({t_b}nm)"))

        elif ctype == "individual_thickness":
            mat = c["material"]
            bound = c["bound"]
            val = c["value_nm"]
            if mat in materials:
                idx = materials.index(mat)
                t = thicknesses[idx]
                if bound == "min":
                    ok = t >= val
                    detail = f"{mat}: {t}nm >= {val}nm"
                elif bound == "max":
                    ok = t <= val
                    detail = f"{mat}: {t}nm <= {val}nm"
                else:  # exact
                    ok = t == val
                    detail = f"{mat}: {t}nm == {val}nm"
                result.checks.append(ConstraintCheckResult(
                    "individual_thickness", ok, detail))

        elif ctype == "total_thickness_sum":
            total = sum(thicknesses)
            val = c["value_nm"]
            if c["bound"] == "max":
                ok = total <= val
                detail = f"sum {total}nm <= {val}nm"
            else:
                ok = total >= val
                detail = f"sum {total}nm >= {val}nm"
            result.checks.append(ConstraintCheckResult(
                "total_thickness_sum", ok, detail))

        elif ctype == "total_thickness_each":
            val = c["value_nm"]
            if c["bound"] == "max":
                ok = all(t <= val for t in thicknesses)
                worst = max(thicknesses) if thicknesses else 0
                detail = f"each <= {val}nm, max layer={worst}nm"
            else:
                ok = all(t >= val for t in thicknesses)
                worst = min(thicknesses) if thicknesses else 0
                detail = f"each >= {val}nm, min layer={worst}nm"
            result.checks.append(ConstraintCheckResult(
                "total_thickness_each", ok, detail))

        elif ctype == "layer_identity":
            pos = c["position"]
            mat = c["material"]
            must_be = c["must_be"]
            if materials:
                actual = materials[0] if pos == "first" else materials[-1]
                if must_be:
                    ok = actual == mat
                    detail = f"{pos} layer must be {mat}, got {actual}"
                else:
                    ok = actual != mat
                    detail = f"{pos} layer must not be {mat}, got {actual}"
                result.checks.append(ConstraintCheckResult(
                    "layer_identity", ok, detail))

    return result
