#!/usr/bin/env python3
"""
Generate Tier-A and Tier-B test sets for INDIGO.

Tier A — same distribution as training, novel structures.
  Generated by calling `generate_dataset.py` with shard ids well outside
  the training range. Same `split_jll_real` polarity as training, so the
  real-material set is identical; only the structures are new.

Tier B — held-out real materials.
  Calls `generate_dataset.py` with `--use-held-out-reals`. The held-out
  materials (Au, TiN, GaAs, Ge, Al2O3, ITO, Pt, ZnO) become the active
  set; the training reals become the holdout. All structures in Tier B
  use *only* held-out reals + fresh synthetic materials.

Note: synthetic Lorentz materials are independent of the real-material
split, so they appear in both tiers. If you want a Tier-B that also
stresses the synthetic-generalisation axis, widen Lorentz parameters or
add a fifth synthetic strategy used only at test time.
"""

import argparse
import subprocess
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--output-root", type=str, default="data/test")
    p.add_argument("--tier-a-rows", type=int, default=50_000)
    p.add_argument("--tier-b-rows", type=int, default=50_000)
    p.add_argument("--rows-per-shard", type=int, default=5000)
    p.add_argument("--tier-a-start-shard-id", type=int, default=1_000_000,
                   help="Pick a shard id range disjoint from training (default: 1M)")
    p.add_argument("--tier-b-start-shard-id", type=int, default=2_000_000,
                   help="Pick a shard id range disjoint from training (default: 2M)")
    p.add_argument("--incidence-angle", type=int, default=0)
    p.add_argument("--jll-materials-dir", type=str, default=None)
    p.add_argument("--skip-existing", action="store_true",
                   help="Skip shards whose parquet already exists")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    common = [
        sys.executable, "scripts/generate_dataset.py",
        "--rows-per-shard", str(args.rows_per_shard),
        "--incidence-angle", str(args.incidence_angle),
    ]
    if args.jll_materials_dir:
        common += ["--jll-materials-dir", args.jll_materials_dir]
    if args.skip_existing:
        common.append("--skip-existing")

    print("[tier-a] generating same-distribution test set...")
    subprocess.run(common + [
        "--total-rows", str(args.tier_a_rows),
        "--start-shard-id", str(args.tier_a_start_shard_id),
        "--output-dir", f"{args.output_root}/tier_a",
    ], check=True)

    print("[tier-b] generating held-out-materials test set...")
    subprocess.run(common + [
        "--total-rows", str(args.tier_b_rows),
        "--start-shard-id", str(args.tier_b_start_shard_id),
        "--output-dir", f"{args.output_root}/tier_b",
        "--use-held-out-reals",
    ], check=True)

    print("[done] test sets written.")


if __name__ == "__main__":
    main()
